### PR TITLE
Adjust Microsoft.FeatureManagement.Telemetry and Microsoft.FeatureManagement.Telemetry.AspNetCore projects

### PR DESCRIPTION
**Pull request by zhiyuanliang-ms**
## Why this PR?

Follow up #417 

## Visible Changes

Rename the project name and update the csproj and sln files.

Update the namespace `Microsoft.FeatureManagement.Telemetry.ApplicationInsights.AspNetCore` to `Microsoft.FeatureManagement.Telemetry.AspNetCore`

### CODE REVIEW

**Comment by rossgrambo** [comment]
Linking to my comment on the previous PR: https://github.com/microsoft/FeatureManagement-Dotnet/pull/417#issuecomment-2043130967

But I am curious- I understood https://github.com/microsoft/FeatureManagement-Dotnet/issues/392 as just a namespace and not a project name update. Was that your intent @zhenlan?

**Comment by zhenlan** [comment]
> But I am curious- I understood #392 as just a namespace and not a project name update. Was that your intent @zhenlan?

Yes, just the namespace change, not the project name change.

**Review by jimmyca15 — CHANGES_REQUESTED** [review]
I don't expect this change is desired. The mentioned issue does not mention updating project names. Merely namespaces.

If that's correct, @zhiyuanliang-ms can you close?

**Comment by zhiyuanliang-ms** [comment]
@jimmyca15 I missed previous discussion about this. Now I get it.

**Pull request closed without merging**
