### PR TITLE
Update FeatureGatedAsyncActionFilter.cs

### PR DESCRIPTION
**Pull request by WeihanLi**
use `context.HttpContext.RequestServices` directly

### CODE REVIEW

**Comment by zhiyuanliang-ms** [comment]
@jimmyca15 It seems like this change is reasonable. Should this PR be approved?

**Review by jimmyca15 — APPROVED** [review]

**Comment by zhiyuanliang-ms** [comment]
@WeihanLi This PR has been approved. Feel free to merge it.

**Comment by WeihanLi** [comment]
@zhiyuanliang-ms thanks, but I think I do not have permission to merge and seemed the status is not updated which also block merge, could you please help check, thanks very much

**Pull request merged**
