### PR TITLE
Fix build warning

### PR DESCRIPTION
**Pull request by zhiyuanliang-ms**
## Why this PR?
Fix [xUnit1031](https://xunit.net/xunit.analyzers/rules/xUnit1031) warning.

Remove nullable property in example projects.

## Visible changes
Update testcases to use async&await.

Update <Nullable> property.

### CODE REVIEW

**Review by Eskibear — APPROVED** [review]

**Comment by rossgrambo** [comment]
> Incorrect nullable

What makes the nullable incorrect here?

**Comment by zhiyuanliang-ms** [comment]
@rossgrambo I am trying to fix these build warnings:

  Microsoft.FeatureManagement -> C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\src\Microsoft.FeatureManagement\bin\Debug\netstandard2.1\Microsoft.FeatureManagement.dll
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\TargetingConsoleApp\Identity\User.cs(10,23): warning CS8618: Non-nullable property 'Id' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\Users\zhiyuanliang\OneDri
ve - Microsoft\Desktop\Dev\FM\examples\TargetingConsoleApp\TargetingConsoleApp.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\TargetingConsoleApp\Identity\User.cs(12,36): warning CS8618: Non-nullable property 'Groups' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\Users\zhiyuanliang\On
eDrive - Microsoft\Desktop\Dev\FM\examples\TargetingConsoleApp\TargetingConsoleApp.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\TargetingConsoleApp\Identity\InMemoryUserRepository.cs(94,20): warning CS8619: Nullability of reference types in value of type 'Task<User?>' doesn't match target type 'Task<User>'. [C:\Users\zhiyuanliang\OneDrive - Mic
rosoft\Desktop\Dev\FM\examples\TargetingConsoleApp\TargetingConsoleApp.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\Models\ErrorViewModel.cs(10,23): warning CS8618: Non-nullable property 'RequestId' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [C:\Users\zhiyuanl
iang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\FeatureFlagDemo.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\HttpContextTargetingContextAccessor.cs(28,39): warning CS8600: Converting null literal or possible null value to non-nullable type. [C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\Fe
atureFlagDemo\FeatureFlagDemo.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\HttpContextTargetingContextAccessor.cs(32,17): warning CS8602: Dereference of a possibly null reference. [C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\FeatureFlagDe
mo.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\HttpContextTargetingContextAccessor.cs(32,75): warning CS8600: Converting null literal or possible null value to non-nullable type. [C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\Fe
atureFlagDemo\FeatureFlagDemo.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\HttpContextTargetingContextAccessor.cs(34,56): warning CS8600: Converting null literal or possible null value to non-nullable type. [C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\Fe
atureFlagDemo\FeatureFlagDemo.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\HttpContextTargetingContextAccessor.cs(34,56): warning CS8604: Possible null reference argument for parameter 'result' in 'ValueTask<TargetingContext>.ValueTask(TargetingContext result)'. [C:\Users\zhiy
uanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\FeatureFlagDemo.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\HttpContextTargetingContextAccessor.cs(55,26): warning CS8602: Dereference of a possibly null reference. [C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\FeatureFlagDe
mo.csproj]
C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\BrowserFilter.cs(44,32): warning CS8602: Dereference of a possibly null reference. [C:\Users\zhiyuanliang\OneDrive - Microsoft\Desktop\Dev\FM\examples\FeatureFlagDemo\FeatureFlagDemo.csproj]

**Comment by rossgrambo** [comment]
I see. We're setting nullable true but not using the nullable ? everywhere where applicable. 

`<nullable>true</nullable>` is automatically added in new projects. I'd prefer we keep it and add the question marks where needed.

**Comment by zhiyuanliang-ms** [comment]
@rossgrambo 
> I'd prefer we keep it and add the question marks where needed.

Then, too many changes are needed, especially for FeatureFlagDemo project. I don't think it's worthy because our feature management projects don't set <nullable> property to true.

**Comment by zhiyuanliang-ms** [comment]
@rossgrambo 
I will follow this PR #305 
I will revert the change for RazorPages but keep the changes for other example projects.

**Pull request merged**
