### PR TITLE
Merge main to release/v2 for 2.6.0-preview release

### PR DESCRIPTION
**Pull request by rossgrambo**

### CODE REVIEW

**Review by avanigupta — APPROVED** [review]

**Comment by avanigupta** [comment]
@jimmyca15, I think this needs to be merged by an admin. There are two issues here: 
- We dont have the buddy build yaml in release/v2 branch yet, so our build requirement is blocking the merge. This PR contains the buddy build pipeline so we should be able to run buddy builds on release/v2 in future.
- Not sure why its showing that the changes are out of date with base branch. I dont see any merge conflicts, all the revert commits are stacked properly. Maybe you have permission to force merge it?

**Comment by jimmyca15** [comment]
@avanigupta it says this branch is behind because of the merge commits in the release branch.

image

**Comment by jimmyca15** [comment]
@avanigupta merged.

**Comment by avanigupta** [comment]
Oh that's strange. We always have extra merge commits in release branches, but I've never seen that message before. Thanks for merging @jimmyca15 !

**Pull request merged**
